# Generated by Django 3.1.2 on 2022-03-19 20:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('combinacion', '0001_initial'),
        ('envio', '0001_initial'),
        ('giftcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formapago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mercadopago', 'Mercado Pago')], max_length=200, verbose_name='Forma de pago')),
                ('tipopago', models.CharField(choices=[('efectivo', 'Efectivo'), ('cbu', 'CBU Transferencia'), ('credit_card', 'Tarjeta de crédito'), ('debit_card', 'Tarjeta de débito'), ('prepaid_card', 'Tarjeta prepaga')], max_length=200, null=True, verbose_name='Tipo de pago')),
                ('id_pagomp', models.CharField(blank=True, default='No aplica', max_length=300, null=True, verbose_name='Id de pago - Mercado Pago')),
                ('fechapago', models.DateField(null=True, verbose_name='Fecha de pago')),
                ('confirmado', models.BooleanField(default=False, verbose_name='¿Pago recibido?')),
                ('url_mp', models.URLField(default=None, editable=False, null=True)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado')], default='pendiente', max_length=300, null=True, verbose_name='Estado del pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(default=True, null=True, verbose_name='¿El pedido está confirmado?')),
                ('estado_armado', models.CharField(choices=[('preparado', 'Preparado'), ('sin_preparar', 'Sin preparar')], default='sin_preparar', max_length=250, null=True, verbose_name='Estado del pedido')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('montofinal', models.FloatField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(limit_value=0, message='El monto tiene que ser mayor o igual 0.')], verbose_name='Monto final del pedido')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=250, null=True, verbose_name='Estado del pedido')),
                ('recibido', models.BooleanField(default=False, null=True, verbose_name='¿Pedido recibido por el cliente?')),
                ('codigo_descuento', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='giftcard.detallecodigodescuento')),
                ('envio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='envio.envio', verbose_name='Envío N°')),
                ('giftcard_descuento', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='giftcard.detallegiftcard')),
                ('pago', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrito.pago', verbose_name='Pago N°')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300)),
                ('evento', models.CharField(choices=[('recepcion_pedido', 'Recepción del pedido'), ('giftcards_asociados', 'Giftcards asociados'), ('ver_pedido', 'Ver pedido')], max_length=300)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrito.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'token',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Detallepedidogiftcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detallegift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftcard.detallegiftcard')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.pedido')),
            ],
            options={
                'verbose_name': 'Detalle del giftcard pedido',
                'verbose_name_plural': 'Detalles de los giftcards pedidos',
                'db_table': 'detalle_pedido_giftcards',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Detallepedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_detalle', models.CharField(choices=[('producto', 'Producto'), ('giftcard', 'Gift Card'), ('combo', 'Box Gift')], default='producto', max_length=250, null=True, verbose_name='Tipo de detalle')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_venta_unitario', models.FloatField(default=0, null=True, verbose_name='Precio de venta')),
                ('subtotal', models.FloatField(default=0, null=True, verbose_name='Subtotal')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('combo', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='combinacion.combo', verbose_name='Box Gift de productos')),
                ('giftcard', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='giftcard.giftcard', verbose_name='Giftcard para regalar')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.pedido', verbose_name='Pedido')),
                ('producto', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto normal')),
            ],
            options={
                'verbose_name': 'Detalle del pedido',
                'verbose_name_plural': 'Detalles del pedido',
                'db_table': 'detalle_pedido',
                'ordering': ['id'],
            },
        ),
    ]
