# Generated by Django 3.1.2 on 2022-03-19 20:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorizacion', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('descripcion', models.TextField(help_text='Ingrese breve despcripción del producto', max_length=1000, verbose_name='Descripción del producto')),
                ('resumen', models.TextField(max_length=200, null=True, verbose_name='Detalle')),
                ('destacado', models.BooleanField(default=False, help_text='¿El producto es destacado?', verbose_name='Destacado')),
                ('stock', models.IntegerField(default=1, verbose_name='Stock disponible')),
                ('fechaprecio', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha del precio')),
                ('preciocosto', models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='El precio tiene que ser mayor o igual 0.')], verbose_name='Precio de costo')),
                ('ganancia', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='La ganancia debe ser mayor o igual 0.')], verbose_name='% de ganancia')),
                ('valorenvio', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='El porcentaje debe ser mayor o igual 0.')], verbose_name='% de envio')),
                ('preciofinal', models.FloatField(editable=False, null=True)),
                ('disponible', models.BooleanField(default=True, null=True, verbose_name='¿Está disponible?')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='imagenes/%Y/%m/%d', verbose_name='Imagen N°1')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='imagenes/%Y/%m/%d', verbose_name='Imagen N°2')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='imagenes/%Y/%m/%d', verbose_name='Imagen N°3')),
                ('calidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorizacion.calidad', verbose_name='Calidad')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorizacion.categoria', verbose_name='Categoría')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorizacion.marca', verbose_name='Marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorizacion.modelo', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Productoproveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'producto_proveedor',
                'ordering': ['id'],
            },
        ),
    ]
