# Generated by Django 3.1.2 on 2022-03-19 20:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(help_text='Ingrese breve despcripción del combo', verbose_name='Descripción')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Está disponible?')),
                ('pganancia', models.IntegerField(null=True, verbose_name='Porcentaje de ganancia')),
                ('preciofinal', models.FloatField(null=True)),
                ('stock', models.IntegerField(default=1, verbose_name='Stock disponible')),
                ('imagen', models.ImageField(null=True, upload_to='combo/%Y/%m/%d', verbose_name='Imagen combo')),
            ],
            options={
                'verbose_name': 'Box Gift',
                'verbose_name_plural': 'Box Gifts',
                'db_table': 'combo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comboproducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Unidades')),
                ('subtotal', models.FloatField(editable=False, null=True)),
                ('combo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='combinacion.combo', verbose_name='Combo asociado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Listado de productos para Box Gifts',
                'verbose_name_plural': 'Combinaciones de productos',
                'db_table': 'combo_producto',
                'ordering': ['id'],
            },
        ),
    ]
