# Generated by Django 3.1.2 on 2022-03-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregfrecuentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(help_text='Ingrese en el campo la pregunta frecuente.', max_length=250, verbose_name='Pregunta frecuente')),
                ('categoria', models.CharField(choices=[('medios-de-pago', 'Medios de pago'), ('compras', 'Compras'), ('pedidos', 'Pedidos'), ('envios', 'Envios'), ('garantias', 'Garantías'), ('devoluciones', 'Devoluciones'), ('giftcards', 'Giftcards'), ('codigos-de-descuento', 'Codigos de descuento'), ('productos', 'Productos'), ('otros', 'Otros temas')], max_length=250, verbose_name='Categoria de pregunta')),
                ('respuesta', models.TextField(max_length=1000, verbose_name='Respuesta a la pregunta frecuente')),
                ('relevancia', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=250)),
                ('destacada', models.BooleanField(blank=True, default=False, verbose_name='¿Pregunta destacada?')),
            ],
            options={
                'verbose_name': 'Pregunta frecuente',
                'verbose_name_plural': 'Pregunas frecuentes',
                'db_table': 'pregunta_frecuente',
                'ordering': ['id'],
            },
        ),
    ]
