# Generated by Django 3.1.2 on 2022-03-19 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lovelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Lovelist ❤', max_length=150, verbose_name='Nombre del Love List')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado')),
            ],
            options={
                'verbose_name': 'Love listado',
                'verbose_name_plural': 'Love listados',
                'db_table': 'lovelist',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Loveproducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lovelist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deseadoslove.lovelist')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Listado de productos',
                'verbose_name_plural': 'Listado de productos',
                'db_table': 'lovelist_producto',
                'ordering': ['id'],
            },
        ),
    ]
