# Generated by Django 3.1.2 on 2022-03-19 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testdeproducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_piel', models.CharField(choices=[('normal', 'Normal'), ('seca', 'Seca'), ('mixta', 'Mixta'), ('grasa', 'Grasa/oleosa')], max_length=250, verbose_name='¿Para que tipo de piel?')),
                ('color_piel', models.CharField(choices=[('clara', 'Clara'), ('morena', 'Morena'), ('oscura', 'Oscura')], max_length=250, verbose_name='¿Para que color de piel?')),
                ('paleta_color', models.CharField(choices=[('pasteles', 'Colores gama pasteles'), ('llamativo', 'Colores gama llamativos/fluor'), ('frios', 'Colores gama frios'), ('calidos', 'Colores gama cálidos'), ('marrones', 'Colores gama marrones/beige')], max_length=250, verbose_name='¿Que tipo de colores lleva?')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto', verbose_name='Producto asociado')),
            ],
            options={
                'verbose_name': 'Test de producto',
                'verbose_name_plural': 'Test de productos',
                'db_table': 'test_producto',
                'ordering': ['id'],
            },
        ),
    ]
