# Generated by Django 3.1.2 on 2022-03-19 20:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('provincial', 'Tipo provincial'), ('nacional', 'Tipo nacional'), ('de_ciudad', 'Transporte del tipo ciudad'), ('internacional', 'Transporte del tipo internacional'), ('ninguno', 'Ninguno')], default='ninguno', max_length=100, null=True, verbose_name='Tipo')),
                ('direccion', models.CharField(max_length=250, unique=True, verbose_name='Direccion sede')),
                ('telefono', models.IntegerField(verbose_name='Número de contac.')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('plazo_entrega', models.CharField(blank=True, max_length=250, null=True, verbose_name='Plazo de entrega habitual')),
                ('precio_servicio', models.FloatField(default=0, null=True, verbose_name='Precio del servicio Standard')),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicacion.ciudad', verbose_name='Ciudad')),
                ('provincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicacion.provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'db_table': 'transporte',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=250, verbose_name='Direccion')),
                ('celular', models.CharField(max_length=300, null=True, verbose_name='Celular de contacto')),
                ('estado', models.BooleanField(default=False, verbose_name='¿Fue enviado?')),
                ('codigo_seguimiento', models.CharField(max_length=100, null=True, unique=True, verbose_name='Código de seguimiento del envío')),
                ('precio_envio', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='El monto tiene que ser mayor o igual 0.')], verbose_name='Precio del envío')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.ciudad', verbose_name='Ciudad')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.provincia', verbose_name='Provincia')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envio.transporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'db_table': 'envio',
                'ordering': ['id'],
            },
        ),
    ]
