# Generated by Django 3.1.2 on 2022-03-19 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=300, verbose_name='Motivo del mensaje')),
                ('mensaje', models.TextField(max_length=600, verbose_name='Consulta de usuario')),
                ('fecha', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha del mensaje')),
                ('respondida', models.BooleanField(default=False, null=True, verbose_name='Respondida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta del usuario',
                'verbose_name_plural': 'Consultas del usuario',
                'db_table': 'consulta_usuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=600, verbose_name='Mensaje de respuesta')),
                ('fecha', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de respuesta')),
                ('visto_mensaje', models.BooleanField(blank=True, default=False, verbose_name='Mensaje visto')),
                ('consulta', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autenticacion.consulta', verbose_name='Consulta del usuario')),
            ],
            options={
                'verbose_name': 'Respuesta para el usuario',
                'verbose_name_plural': 'Respuestas para el usuario',
                'db_table': 'respuesta_usuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Perfilusuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(null=True, unique=True, verbose_name='DNI o CUIT')),
                ('tipo_usuario', models.CharField(choices=[('consumidor_final', 'Consumidor final'), ('responsable_inscripto', 'Responsable inscripto'), ('monotributista', 'Monotributista')], default='consumidor_final', max_length=100, null=True, verbose_name='Tipo de usuario')),
                ('fnacimiento', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('otro', 'Otro')], default='otro', max_length=100, null=True, verbose_name='Sexo')),
                ('fotoperfil', models.ImageField(blank=True, null=True, upload_to='perfil-foto/%Y/%m/%d/', verbose_name='Foto de perfil')),
                ('ciudad', models.ForeignKey(default='Rio Grande', on_delete=django.db.models.deletion.CASCADE, to='ubicacion.ciudad', verbose_name='Ciudad')),
                ('provincia', models.ForeignKey(default='Tierra del Fuego', on_delete=django.db.models.deletion.CASCADE, to='ubicacion.provincia', verbose_name='Provincia')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfil de usuarios',
                'db_table': 'perfil_usuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=150, verbose_name='Telefono/Celular')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('numero', models.IntegerField(verbose_name='Número de casa')),
                ('piso_departamento', models.CharField(blank=True, max_length=100, verbose_name='Piso y departamento')),
                ('destacada', models.BooleanField(blank=True, default=False)),
                ('ciudad', models.ForeignKey(default='Rio Grande', on_delete=django.db.models.deletion.CASCADE, to='ubicacion.ciudad')),
                ('provincia', models.ForeignKey(default='Tierra del Fuego', on_delete=django.db.models.deletion.CASCADE, to='ubicacion.provincia')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacion.perfilusuario')),
            ],
            options={
                'verbose_name': 'Dirección usuario',
                'verbose_name_plural': 'Libreta de direcciones',
                'db_table': 'direccion_usuario',
                'ordering': ['id'],
            },
        ),
    ]
