# Generated by Django 3.1.2 on 2022-03-19 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonsocial', models.CharField(max_length=100, unique=True, verbose_name='Razon Social')),
                ('cuit', models.CharField(help_text='Ingrese su cuit aquí', max_length=200, null=True, verbose_name='Cuit')),
                ('tipo', models.CharField(blank=True, choices=[('provincial', 'Tipo Provincial'), ('nacional', 'Tipo Nacional'), ('internacional', 'Tipo Internacional'), ('ninguno', 'Ninguno')], default='ninguno', max_length=200, null=True, verbose_name='Tipo')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('email', models.EmailField(help_text='Ingrese su email aquí', max_length=254)),
                ('telefono', models.CharField(max_length=200, null=True, verbose_name='Teléfono')),
                ('contacto', models.CharField(max_length=100, verbose_name='Contacto de referencia')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.ciudad', verbose_name='Ciudad')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['id'],
            },
        ),
    ]
