# Generated by Django 3.1.2 on 2022-03-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxpedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('fecha_d', models.DateField(verbose_name='Fecha desde')),
                ('fecha_h', models.DateField(verbose_name='Fecha hasta')),
                ('listado', models.TextField(max_length=1500, verbose_name='Listado de productos')),
                ('detalles', models.TextField(max_length=400, verbose_name='Detalles del pedido')),
                ('link_publicacion', models.URLField(verbose_name='Link de publicación - Fotos en Instagram')),
            ],
            options={
                'verbose_name': 'Proximo pedido',
                'verbose_name_plural': 'Próximos pedidos',
                'db_table': 'proximos-pedidos',
                'ordering': ['id'],
            },
        ),
    ]
