# Generated by Django 3.1.2 on 2022-03-19 20:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigodescuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=250, unique=True, verbose_name='Código de descuento')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre del descuento')),
                ('valor', models.IntegerField(blank=True, default=0, help_text='Rellenar el campo con el procentaje de descuento', null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='El monto tiene que ser mayor o igual 0.')], verbose_name='Descuento %')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio (Comienzo)')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin (Caducidad)')),
            ],
            options={
                'verbose_name': 'Código de descuento',
                'verbose_name_plural': 'Códigos de descuento',
                'db_table': 'codigo_descuento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Giftcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=400, verbose_name='Descripción')),
                ('slug', models.SlugField(verbose_name='Slug -> Url amigable')),
                ('preciofinal', models.IntegerField(default=0, verbose_name='Precio del Giftcard')),
                ('disponible', models.BooleanField(default=True, null=True, verbose_name='¿Está disponible?')),
                ('stock', models.IntegerField(default=1, verbose_name='Stock disponible')),
                ('temporada', models.CharField(blank=True, max_length=250, null=True, verbose_name='Temporada del GiftCard')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='giftcard/%Y/%m/%d', verbose_name='Imagen del giftcard')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='giftcard/%Y/%m/%d', verbose_name='Imagen 2 del giftcard')),
            ],
            options={
                'verbose_name': 'Gift Card',
                'verbose_name_plural': 'Gift Cards',
                'db_table': 'gift_card',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Detallegiftcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('usado', models.BooleanField(default=False, verbose_name='¿Ya fué utilizado?')),
                ('valor_descuento', models.FloatField(default=0, null=True, verbose_name='Descuento aplicado en $')),
                ('nombre_amigo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ingresa el nombre del amigo')),
                ('correo_amigo', models.EmailField(blank=True, max_length=300, null=True, verbose_name='Email del amigo')),
                ('nro_tarjeta', models.IntegerField(null=True)),
                ('codigo_seguridad', models.IntegerField(null=True)),
                ('giftcard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='giftcard.giftcard', verbose_name='Giftcard asociado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autenticacion.perfilusuario', verbose_name='Usuario asociado')),
            ],
            options={
                'verbose_name': 'Listado de Gift Card',
                'verbose_name_plural': 'Listados de Giftcards',
                'db_table': 'detalle_giftcard',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Detallecodigodescuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('codigo_texto', models.CharField(max_length=300, null=True, verbose_name='Código aplicado')),
                ('porcentaje', models.IntegerField(verbose_name='Porcentaje aplicado')),
                ('descuento_aplicado', models.FloatField(null=True, verbose_name='Descuento aplicado en el pedido')),
                ('codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='giftcard.codigodescuento', verbose_name='Código asociado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autenticacion.perfilusuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Listado de códigos aplicados',
                'verbose_name_plural': 'Listados de códigos aplicados',
                'db_table': 'detalle_codigodescuento',
                'ordering': ['id'],
            },
        ),
    ]
