# Generated by Django 3.1.2 on 2022-03-19 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de articulos')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Recomendado y más pedido',
                'verbose_name_plural': 'Recomendados y más pedidos',
                'db_table': 'recomendados',
                'ordering': ['id'],
            },
        ),
    ]
